<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="22061" started-at="2020-08-19T02:25:14Z" finished-at="2020-08-19T02:25:36Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="22061" started-at="2020-08-19T02:25:14Z" finished-at="2020-08-19T02:25:36Z">
      <class name="com.actitime.qa.testcases.UsersPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.actitime.qa.testcases.UsersPageTest@59f99ea]" name="setUp" is-config="true" duration-ms="18593" started-at="2020-08-19T03:25:14Z" finished-at="2020-08-19T03:25:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="createNewUserTest()[pri:0, instance:com.actitime.qa.testcases.UsersPageTest@59f99ea]" name="createNewUserTest" duration-ms="3442" started-at="2020-08-19T03:25:32Z" finished-at="2020-08-19T03:25:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.actitime.qa.util.TestUtil.readDataFromExcel(TestUtil.java:30)
	at com.actitime.qa.testcases.UsersPageTest.createNewUserTest(UsersPageTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUserTest -->
      </class> <!-- com.actitime.qa.testcases.UsersPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
